# Generated by Django 2.0 on 2017-12-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('date_time', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField()),
                ('success', models.IntegerField()),
            ],
        ),
    ]
