# Generated by Django 2.0 on 2017-12-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
